version: '3.4'

services:
  mysqlserverapi:
    image: mysqlserverapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8081:80
    env_file: 
      - .env
    container_name: mysql-api-worker
    volumes: 
      - "C:\\Users\\Shlomi\\Desktop\\mysql-server\\server:/usr/src/app/server/"
